version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: sp2danny/friendlyhello:part1
    deploy:
      replicas: 15
      resources:
        limits:
          cpus: "2.5"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:4000"
    networks:
      - webnet
networks:
  webnet:

